### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, string given

### ISSUE THREAD

**Issue by jringeisen** [AtaneNL/SignRequest#7]
I have implemented exactly as stated in the ReadMe but the sendSignRequest() keeps throwing this error. I tried getting rid of the foreach of $recipients to see what would happen and then I get the following error:

`{"signers":[{"non_field_errors":["Invalid data. Expected a dictionary, but got unicode."]},{"non_field_errors":["Invalid data. Expected a dictionary, but got unicode."]}]}`

Any ideas?

**Comment by paneidos** [comment]
It seems the README is a little out-of-date.

A recipient should be a keyed array, like this:
```
$recipient = [
            'last_name'           => 'Smith',
            'email'               => 'smith@example.com',
            'verify_phone_number' => false,
            'needs_to_sign'       => true,
            'order'               => 0,
            'language'            => 'nl',
            'force_language'      => true,
            'redirect_url'        => 'http://www.example.com/thank-you-for-signing',  // redirect here after the user finished signing
        ];
$recipients = [$recipient];
```

I'll keep this issue open until the README is updated or we can accept scalar values in the recipients array.

**Comment by jringeisen** [comment]
I was getting another error for verify_phone_number, it was asking me to add a number with the + symbol so I removed that key and it worked. Thanks.

**Comment by jringeisen** [comment]
I am in the process of implementing the API into my website but the documentation is very bland and doesn't provide much information so I am having a difficult time figuring out what its capable of. For instance, my website is a CRM for photographers and I am adding the ability for them to upload contracts and send them to their clients to be signed. The API doesn't seem to allow for customizing the emails that are sent to the recipients. I would like the email that is sent to have the users business name on it, not mine (the admins).

**Comment by o-daan** [comment]
Hi, the $message parameter in the sendSignRequest method allows you to set the message that the recipients see. The message will be the same for all recipients of that particular sign request. Please refer to [https://signrequest.com/api/v1/docs/#customize-email](https://signrequest.com/api/v1/docs/#customize-email) for more information.
